-- Generated fish base values + mutation price multipliers
-- Source: ReplicatedStorage.common.presets.items.fish + mutations scan

local FishBaseValue = {
	["Blobfish"] = 75,
	["Bluefin Tuna"] = 36,
	["Piranha"] = 44,
	["Sea Horse"] = 250,
	["Barracuda"] = 20,
	["Blue Tang"] = 14,
	["Clownfish"] = 12,
	["Inflated Pufferfish"] = 26,
	["Lionfish"] = 20,
	["Mahi Mahi"] = 8,
	["Pufferfish"] = 13,
	["Salmon"] = 9,
	["Tang"] = 12,
	["Ancient Shark"] = 50,
	["Bigmouthfish"] = 76,
	["Blackfin Tuna"] = 16,
	["Cavefish"] = 22,
	["Cod"] = 18,
	["Grouper"] = 28,
	["Pompano"] = 14,
	["Scorpionfish"] = 60,
	["Shark"] = 40,
	["Dragonfish"] = 70,
	["Eyefish"] = 160,
	["Hammer Shark"] = 48,
	["Jellyfish"] = 35,
	["Napoleon"] = 20,
	["Narwhal"] = 18,
	["Pacific Fanfish"] = 20,
	["Sailfish"] = 40,
	["Sunfish"] = 17,
	["Whale"] = 40,
	["Anglerfish"] = 35,
	["King Anglerfish"] = 45,
	["Discus"] = 25,
	["Jaguar Shark"] = 50,
	["Mosasaurus"] = 50,
	["Pelican Eel"] = 75,
	["Sacabambaspis"] = 150,
	["Sea Turtle"] = 20,
	["Tambaqui"] = 18,
	["Toucan Fish"] = 90,
	["Trout"] = 24,
	["Alien"] = 140,
	["Angel"] = 300,
	["Atlantic Octopus"] = 60,
	["Basking Shark"] = 85,
	["Boxfish"] = 32,
	["Catfish"] = 32,
	["Largemouth Bass"] = 65,
	["Manta Ray"] = 48,
	["Orca"] = 63,
	["Phantom Jelly"] = 145,
	["Sea Angel"] = 75,
	["Sockeye Salmon"] = 100,
	["Squid"] = 65,
	["Stingray"] = 35,
	["Surubim"] = 68,
	["Thresher Shark"] = 82,
}

local MutationPriceMultiplier = {
	["Abyssal"] = 8.5,
	["Albino"] = 1.3,
	["Angelic"] = 7.77,
	["Banana"] = 1.5,
	["Cactus"] = 1.45,
	["Coral"] = 1.1,
	["Cupid"] = 1.4,
	["Fairy"] = 2.3,
	["Fossil"] = 1.75,
	["Golden"] = 2,
	["Grounded"] = 2.8,
	["Invisible"] = 2.4,
	["Jade"] = 4,
	["Liquid"] = 2.5,
	["Lonely"] = 2,
	["Metal"] = 1.2,
	["Moss"] = 1.1,
	["Negative"] = 2,
	["Neon"] = 2.8,
	["Poop"] = 0.333,
	["Rock"] = 1,
	["Rooted"] = 3.6,
	["Sand"] = 1.25,
	["Shadow"] = 6.66,
	["Spirit"] = 1.7,
	["Toxic"] = 3.75,
	["Transparent"] = 1.35,
	["Ultraviolet"] = 3.6,
}

return {
	FishBaseValue = FishBaseValue,
	MutationPriceMultiplier = MutationPriceMultiplier,
}

